# Github actions pipeline with matrix strategy. 
name: Node.js CI with Matrix Strategy
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [18, 20, 22, 24]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node }}
                cache: 'npm'
            # - name: Install dependencies
            #   run: npm ci
            # - name: Run tests
            #   run: npm test
            # check npm version
            - name: Check npm version
              run: npm --version
              